services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    networks:
      - shared_network
    user: "www-data:www-data"
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=
      - DB_HOST=mariadb_local
      - DB_PORT=3306
      - DB_DATABASE=sistema_carga_horaria
      - DB_USERNAME=user
      - DB_PASSWORD=user123
      - JWT_SECRET=3UQRwY1sg7OmNkrgOL2CMD9h05k09VhTIGMJPBW7V82OD77YwuGxOR894ECRUEvYyDHcw6h5kl2mKIOctwb0zjKgkf3CPDolxttDOMpC8irTSHiavmHO6CfD8EQ6ATum
      - API_URL=http://api_csharp_local:8080/api/
    env_file:
      - .env

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - shared_network
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

networks:
  shared_network:
    external: true
