services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_DATABASE: sistema_carga_horaria
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - shared_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_local
    restart: always
    ports:
      - "7050:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mariadb
    networks:
      - shared_network

  application:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_bridge
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_bridge

volumes:
  mariadb_data:
    driver: local

networks:
  shared_network:  # Nome fixo para a rede compartilhada
    name: shared_network
    driver: bridge

