name: Laravel Deploy Only

on:
  push:
    branches: [ main, develop ]

jobs:
  prepare-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixar o código
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Criar pacote limpo
    - name: Create raw package
      run: |
        # Remove arquivos desnecessários
        rm -rf .git .github node_modules vendor
        # Cria o zip
        zip -r deployment.zip . -x '*.env*'

    # Passo 3: Salvar o pacote
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: raw-laravel-code
        path: deployment.zip

    # Passo 4: Deploy via SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          cd /home/marcilio/app
          docker-compose down
          rm -rf src/*
          unzip -q /home/runner/work/_temp/*/deployment.zip -d src/
          cd src
          php artisan optimize:clear
          cd ..
          make up-app
          echo "Deploy finalizado! ✅"
