name: Laravel Direct Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Criar o pacote ZIP limpo
    - name: Create raw package
      run: |
        # Remove arquivos que não devem ser enviados
        rm -rf .git .github .env node_modules vendor
        # Cria o ZIP mantendo a estrutura de pastas
        zip -r deployment.zip .

    # Passo 3: Enviar o ZIP para o servidor via SCP
    - name: Upload ZIP to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "deployment.zip"
        target: "/home/marcilio/app"

    # Passo 4: Executar comandos no servidor via SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          cd /home/marcilio/app
          docker-compose down
          
          # Verifica se o ZIP foi enviado
          if [ ! -f deployment.zip ]; then
            echo "Erro: deployment.zip não encontrado!"
            exit 1
          fi
          
          # Limpa o diretório e descompacta o ZIP
          rm -rf src/*
          unzip -q deployment.zip -d src/
          rm deployment.zip  # Remove o ZIP após descompactar
          
          # Comandos pós-deploy
          cd src
          php artisan optimize:clear
          cd ..
          make up-app
          echo "Deploy realizado com sucesso!"
